# Generated by Django 6.0.6 on 2026-06-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=20)),
                ('provider_user_id', models.CharField(db_index=True, max_length=255)),
                ('email_linked', models.EmailField(db_index=True, max_length=254)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_provider_account'), models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'), models.UniqueConstraint(fields=('provider', 'email_linked'), name='unique_provider_email')],
            },
        ),
    ]
